method: onet
data:
  # dataset: Shapes3D
  path: data/ShapeNet
  img_folder: img_choy2016
  # classes: ['04401088', '03211117']  # telephone, display
  # classes: ['04090263']  # rifle
  classes: ['04401088', '03211117', '04090263']
  img_size: 224 
  points_subsample: 2048 
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: resnet18
  encoder_path: out/vae-base-and-novel/model_best.pt
  c_dim: 256 
  z_dim: 0
training:
  out_dir:  out/img/onet-fsl-zero-shot-baseline
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
test:
  threshold: 0.2
  model_file: model_best.pt
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

