method: vae
data:
  dataset: Shapes3D
  # dataset: images 
  path: data/ShapeNet
  classes: ['04401088', '03211117', '04090263']  # phone, display, rifle
  input_type: img
  train_split: train
  val_split: val
  test_split: test
  img_folder: img_choy2016
  img_size: 224 
  img_with_camera: false
  img_augment: false
  n_views: 24
  with_transforms: false
model:
  multi_gpu: false
  c_dim: 512
  z_dim: 0
training:
  out_dir:  out/vae-base-and-novel
  batch_size: 64
  print_every: 10
  visualize_every: 1000 
  checkpoint_every: 1000 
  validate_every: 1000
  backup_every: 100000
  eval_sample: false
  model_selection_metric: loss
  model_selection_mode: minimize
test:
  model_file: model_best.pt
